# Generated by Django 6.1.1 on 2026-09-14 04:03

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0002_issue_analysis_issue_resolution_image_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='issue',
            index=models.Index(fields=['category'], name='issues_issu_categor_12b737_idx'),
        ),
        migrations.AddIndex(
            model_name='issue',
            index=models.Index(fields=['status'], name='issues_issu_status_003ba6_idx'),
        ),
        migrations.AddIndex(
            model_name='issue',
            index=models.Index(fields=['reporter', 'created_at'], name='issues_issu_reporte_33c0c8_idx'),
        ),
    ]
