# Generated by Django 6.1.1 on 2026-09-19 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0003_issue_issues_issu_categor_12b737_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='image_source',
            field=models.CharField(blank=True, choices=[('camera', 'Camera'), ('gallery', 'Gallery')], default='', help_text='Whether the photo was captured on-device or picked from the gallery.', max_length=16),
        ),
    ]
