# Generated by Django 6.1.1 on 2026-09-23 14:19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0004_issue_image_source'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='client_request_id',
            field=models.CharField(blank=True, db_index=True, default=None, help_text='Opaque client-provided idempotency key, unique per reporter.', max_length=128, null=True),
        ),
        migrations.AddConstraint(
            model_name='issue',
            constraint=models.UniqueConstraint(condition=models.Q(('client_request_id__isnull', True), _negated=True), fields=('reporter', 'client_request_id'), name='unique_reporter_request_id'),
        ),
    ]
