# Generated by Django 6.1.1 on 2026-09-26 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0005_client_request_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='image_brightness',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='issue',
            name='image_dhash',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='issue',
            name='priority',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='issue',
            name='priority_label',
            field=models.CharField(blank=True, default='low', max_length=16),
        ),
        migrations.AddField(
            model_name='issue',
            name='priority_reasons',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
