# Generated by Django 6.1.1 on 2026-09-26 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0006_issue_image_brightness_issue_image_dhash_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='priority_model_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='issue',
            name='vision',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='issue',
            name='vision_embedding',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
